//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intercambio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intercambio()
        {
            this.Intercambio_Detalle = new HashSet<Intercambio_Detalle>();
        }
    
        public int id { get; set; }
        public decimal montoRecibido { get; set; }
        public decimal montoDado { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intercambio_Detalle> Intercambio_Detalle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
