//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intercambio_Detalle
    {
        public int id { get; set; }
        public bool condicion { get; set; }
        public bool tipo { get; set; }
        public int intercambio_id { get; set; }
        public int producto_id { get; set; }
    
        public virtual Intercambio Intercambio { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
