//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public bool prioridad { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estado { get; set; }
        public string color { get; set; }
        public int producto_id { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
