//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertasEspecial_Producto
    {
        public int id { get; set; }
        public decimal descuento { get; set; }
        public int categoria_id { get; set; }
        public int ofertasEspeciales_id { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual OfertasEspecial OfertasEspecial { get; set; }
    }
}
