//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preorden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preorden()
        {
            this.Cliente_Preorden = new HashSet<Cliente_Preorden>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fechaLanzamiento { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> montoInicial { get; set; }
        public bool estado { get; set; }
        public int producto_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Preorden> Cliente_Preorden { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
