//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIVIZZEntities : DbContext
    {
        public SIVIZZEntities()
            : base("name=SIVIZZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente_Preorden> Cliente_Preorden { get; set; }
        public virtual DbSet<Consola> Consola { get; set; }
        public virtual DbSet<Intercambio> Intercambio { get; set; }
        public virtual DbSet<Intercambio_Detalle> Intercambio_Detalle { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<OfertasEspecial> OfertasEspecial { get; set; }
        public virtual DbSet<OfertasEspecial_Producto> OfertasEspecial_Producto { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Preorden> Preorden { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Rol_Permisos> Rol_Permisos { get; set; }
        public virtual DbSet<TipoPago> TipoPago { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Venta_Detalle> Venta_Detalle { get; set; }
        public virtual DbSet<Videojuego_Inventario> Videojuego_Inventario { get; set; }
    }
}
